version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Pass123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql # Persists data even if container is removed

  api:
    build:
      context: .
      dockerfile: JWTWithCoreApis/Dockerfile
    container_name: dotnet_api
    depends_on:
      - db
    ports:
      - "5000:8080" # Maps local port 5000 to container port 8080
    environment:
      - ConnectionStrings__DefaultConnection=Server=DESKTOP-VRMFV23\\SQLEXPRESS;Database=MVCCoreDb;Trusted_Connection=True;TrustServerCertificate=True

volumes:
  mssql_data: