// <auto-generated />
using System;
using JWTWithCoreApis.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JWTWithCoreApis.Migrations
{
    [DbContext(typeof(CoreapidbContext))]
    [Migration("20260710100753_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("apiuser")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JWTWithCoreApis.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<double?>("Gst")
                        .HasColumnType("float")
                        .HasColumnName("gst");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("product_name");

                    b.Property<double?>("Rate")
                        .HasColumnType("float")
                        .HasColumnName("rate");

                    b.Property<double?>("StockQuantity")
                        .HasColumnType("float")
                        .HasColumnName("stock_quantity");

                    b.HasKey("ProductId")
                        .HasName("PK__products__47027DF521A3E01B");

                    b.ToTable("products", "dbo");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.TblCustomer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CustomerId")
                        .HasName("PK__tblCusto__A4AE64D82C6760C1");

                    b.HasIndex(new[] { "MobileNumber" }, "UQ__tblCusto__250375B1B4E27C0B")
                        .IsUnique();

                    b.HasIndex(new[] { "MobileNumber" }, "UQ__tblCusto__250375B1D11C89D5")
                        .IsUnique();

                    b.HasIndex(new[] { "EmailAddress" }, "UQ__tblCusto__49A147403662EB00")
                        .IsUnique();

                    b.HasIndex(new[] { "EmailAddress" }, "UQ__tblCusto__49A147409F4685E8")
                        .IsUnique();

                    b.ToTable("tblCustomers", "dbo");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.TblInvoiceDetail", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("InvoiceId")
                        .HasName("PK__tblInvoi__D796AAB521E7BE2A");

                    b.HasIndex("CustomerId");

                    b.ToTable("tblInvoiceDetails", "dbo");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.TblInvoicePayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<double?>("PaymentAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PaymentId")
                        .HasName("PK__tblInvoi__9B556A3810C69400");

                    b.HasIndex("InvoiceId");

                    b.ToTable("tblInvoicePayments", "dbo");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.TblInvoiceProduct", b =>
                {
                    b.Property<int>("InvoiceProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceProductId"));

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("InvoiceProductId")
                        .HasName("PK__tblInvoi__D032D0C95C5D3F80");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("tblInvoiceProducts", "dbo");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.TblProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("Gst")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId")
                        .HasName("PK__tblProdu__B40CC6CD9AE61534");

                    b.ToTable("tblProducts", "dbo");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.Tblemployee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("designation");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("employee_code");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("employee_name");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.HasKey("EmployeeId")
                        .HasName("PK__tblemplo__C52E0BA83EF6F507");

                    b.HasIndex(new[] { "EmployeeCode" }, "UQ__tblemplo__B0AA7345CDC14887")
                        .IsUnique();

                    b.ToTable("tblemployees", "dbo");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.TblstudentDetail", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email_address");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("StudentName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("student_name");

                    b.HasKey("StudentId")
                        .HasName("PK__tblstude__2A33069A6E0ABE11");

                    b.ToTable("tblstudent_details", "dbo");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.Tbluser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__tblusers__1788CC4C53F2595C");

                    b.ToTable("tblusers", "dbo");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.TblInvoiceDetail", b =>
                {
                    b.HasOne("JWTWithCoreApis.Models.TblCustomer", "Customer")
                        .WithMany("TblInvoiceDetails")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fkcid");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.TblInvoicePayment", b =>
                {
                    b.HasOne("JWTWithCoreApis.Models.TblInvoiceDetail", "Invoice")
                        .WithMany("TblInvoicePayments")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("fkincid");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.TblInvoiceProduct", b =>
                {
                    b.HasOne("JWTWithCoreApis.Models.TblInvoiceDetail", "Invoice")
                        .WithMany("TblInvoiceProducts")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("fkinvoiceid");

                    b.HasOne("JWTWithCoreApis.Models.TblProduct", "Product")
                        .WithMany("TblInvoiceProducts")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fkproductid");

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.TblCustomer", b =>
                {
                    b.Navigation("TblInvoiceDetails");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.TblInvoiceDetail", b =>
                {
                    b.Navigation("TblInvoicePayments");

                    b.Navigation("TblInvoiceProducts");
                });

            modelBuilder.Entity("JWTWithCoreApis.Models.TblProduct", b =>
                {
                    b.Navigation("TblInvoiceProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
